### ISSUE TITLE
Hidpi

### ISSUE THREAD

**Issue by shenhfhep** [andrewlsa/Matebook-14-2019-Hackintosh#1]
你好,请问用的别人的efi可以用你的hidpi的文件吗.如果可以请问该如何使用?bigsur没有找到/Library/Displays/ 这个Display目录啊

**Comment by andrewlsa** [comment]
HiDPI通用的。
新建路径文件夹就行。

**Comment by shenhfhep** [comment]
> HiDPI通用的。
> 新建路径文件夹就行。

请问是吧hidpi整个文件夹放进去吗,还是说哪个文件? 如果要改其他的分辨率的话需要如何操作?谢谢

**Comment by andrewlsa** [comment]
里面两个文件。
适配14 2160x1440的分辨率这几个已经够用。
